name: Dynamic CI

on: push

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.set-outputs.outputs.frontend_changed }}
      backend_changed: ${{ steps.set-outputs.outputs.backend_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-outputs
        run: |
          echo "frontend_changed=false" >> $GITHUB_ENV
          echo "backend_changed=false" >> $GITHUB_ENV
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q 'packages/frontend'; then
            echo "frontend_changed=true" >> $GITHUB_ENV
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q 'packages/backend'; then
            echo "backend_changed=true" >> $GITHUB_ENV
          fi
          echo "::set-output name=frontend_changed::$frontend_changed"
          echo "::set-output name=backend_changed::$backend_changed"

  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: |
          cd packages/frontend
          yarn build

  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Backend
        run: |
          cd packages/backend
          yarn build
